services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    user: "1000:1000" 